project:
  type: website
  output-dir: docs
website:
  title: "Fran Pontin"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cv.qmd
      - projects.qmd
      - href: presentations.qmd
        text: Presentations
      - href: teaching.qmd
        text: Teaching
      - resources.qmd

format:
  html:
    theme: minty
    css: styles.css
    toc: true



